package com.example.genshinstatistics.constants

import com.example.genshinstatistics.R
import com.example.genshinstatistics.enums.ItemType
import com.example.genshinstatistics.model.Item
import com.example.genshinstatistics.enums.Region

object ArchiveCharacterData {
    val Characthers: List<Item> by lazy {
        listOf(
            // 5-Star Characters
            Item(
                id = 1,
                name = "Albedo",
                region = Region.MONDSTADT,
                iconBgColor = R.drawable.ic_geo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-albedo.png",
                birthdate = "09/13",
                itemTypeIcon = R.drawable.ic_element_geo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 2,
                name = "Alhaitham",
                region = Region.SUMERU,
                iconBgColor = R.drawable.ic_dendro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-alhatham.png",
                birthdate = "09/26",
                itemTypeIcon = R.drawable.ic_element_dendro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 3,
                name = "Aloy",
                region = Region.UNKNOWN,
                iconBgColor = R.drawable.ic_cryo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-aloy.png",
                birthdate = "02/06",
                itemTypeIcon = R.drawable.ic_element_cryo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 4,
                name = "Arataki Itto",
                region = Region.INAZUMA,
                iconBgColor = R.drawable.ic_geo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-itto.png",
                birthdate = "06/01",
                itemTypeIcon = R.drawable.ic_element_geo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 5,
                name = "Arlecchino",
                region = Region.SNEZHNAYA,
                iconBgColor = R.drawable.ic_pyro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-arlecchino.png",
                birthdate = "08/22",
                itemTypeIcon = R.drawable.ic_element_pyro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 6,
                name = "Baizhu",
                region = Region.LIYUE,
                iconBgColor = R.drawable.ic_dendro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-baizhu.png",
                birthdate = "04/25",
                itemTypeIcon = R.drawable.ic_element_dendro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 7,
                name = "Chasca",
                region = Region.NATLAN,
                iconBgColor = R.drawable.ic_anemo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic_chasca.png",
                birthdate = "12/10",
                itemTypeIcon = R.drawable.ic_element_anemo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 8,
                name = "Chiori",
                region = Region.INAZUMA,
                iconBgColor = R.drawable.ic_geo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic_chiori.png",
                birthdate = "08/17",
                itemTypeIcon = R.drawable.ic_element_geo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 9,
                name = "Citlali",
                region = Region.NATLAN,
                iconBgColor = R.drawable.ic_cryo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic_citlali.png",
                birthdate = "01/20",
                itemTypeIcon = R.drawable.ic_element_cryo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 10,
                name = "Clorinde",
                region = Region.FONTAINE,
                iconBgColor = R.drawable.ic_electro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic_clorinde.png",
                birthdate = "09/20",
                itemTypeIcon = R.drawable.ic_element_electro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 11,
                name = "Cyno",
                region = Region.SUMERU,
                iconBgColor = R.drawable.ic_electro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-cyno.png",
                birthdate = "07/23",
                itemTypeIcon = R.drawable.ic_element_electro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 12,
                name = "Dehya",
                region = Region.SUMERU,
                iconBgColor = R.drawable.ic_pyro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-dehya.png",
                birthdate = "04/25",
                itemTypeIcon = R.drawable.ic_element_pyro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 13,
                name = "Diluc",
                region = Region.MONDSTADT,
                iconBgColor = R.drawable.ic_pyro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-diluc.png",
                birthdate = "04/30",
                itemTypeIcon = R.drawable.ic_element_pyro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 14,
                name = "Emilie",
                region = Region.FONTAINE,
                iconBgColor = R.drawable.ic_dendro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic_emilie.png",
                birthdate = "09/28",
                itemTypeIcon = R.drawable.ic_element_dendro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 15,
                name = "Eula",
                region = Region.MONDSTADT,
                iconBgColor = R.drawable.ic_cryo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-eula.png",
                birthdate = "10/25",
                itemTypeIcon = R.drawable.ic_element_cryo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 16,
                name = "Furina",
                region = Region.FONTAINE,
                iconBgColor = R.drawable.ic_hydro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-furina.png",
                birthdate = "10/13",
                itemTypeIcon = R.drawable.ic_element_hydro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 17,
                name = "Ganyu",
                region = Region.LIYUE,
                iconBgColor = R.drawable.ic_cryo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-ganyu.png",
                birthdate = "12/02",
                itemTypeIcon = R.drawable.ic_element_cryo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 18,
                name = "Hu Tao",
                region = Region.LIYUE,
                iconBgColor = R.drawable.ic_pyro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-hutao.png",
                birthdate = "07/15",
                itemTypeIcon = R.drawable.ic_element_pyro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 19,
                name = "Jean",
                region = Region.MONDSTADT,
                iconBgColor = R.drawable.ic_anemo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-jean.png",
                birthdate = "03/14",
                itemTypeIcon = R.drawable.ic_element_anemo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 20,
                name = "Kaedehara Kazuha",
                region = Region.INAZUMA,
                iconBgColor = R.drawable.ic_anemo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-kazuha.png",
                birthdate = "10/29",
                itemTypeIcon = R.drawable.ic_element_anemo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 21,
                name = "Kamisato Ayaka",
                region = Region.INAZUMA,
                iconBgColor = R.drawable.ic_cryo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-ayaka.png",
                birthdate = "09/28",
                itemTypeIcon = R.drawable.ic_element_cryo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 22,
                name = "Kamisato Ayato",
                region = Region.INAZUMA,
                iconBgColor = R.drawable.ic_hydro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic_ayaka.png",
                birthdate = "03/26",
                itemTypeIcon = R.drawable.ic_element_hydro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 23,
                name = "Keqing",
                region = Region.LIYUE,
                iconBgColor = R.drawable.ic_electro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-keqing.png",
                birthdate = "11/20",
                itemTypeIcon = R.drawable.ic_element_electro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 24,
                name = "Kinich",
                region = Region.NATLAN,
                iconBgColor = R.drawable.ic_dendro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic_kinich.png",
                birthdate = "11/11",
                itemTypeIcon = R.drawable.ic_element_dendro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 25,
                name = "Klee",
                region = Region.MONDSTADT,
                iconBgColor = R.drawable.ic_pyro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-klee.png",
                birthdate = "07/27",
                itemTypeIcon = R.drawable.ic_element_pyro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 26,
                name = "Lyney",
                region = Region.FONTAINE,
                iconBgColor = R.drawable.ic_pyro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-liney.png",
                birthdate = "02/02",
                itemTypeIcon = R.drawable.ic_element_pyro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 27,
                name = "Mona",
                region = Region.MONDSTADT,
                iconBgColor = R.drawable.ic_hydro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-mona.png",
                birthdate = "08/31",
                itemTypeIcon = R.drawable.ic_element_hydro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 28,
                name = "Mualani",
                region = Region.NATLAN,
                iconBgColor = R.drawable.ic_hydro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic_mualani.png",
                birthdate = "08/03",
                itemTypeIcon = R.drawable.ic_element_hydro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 29,
                name = "Nahida",
                region = Region.SUMERU,
                iconBgColor = R.drawable.ic_dendro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-nahida.png",
                birthdate = "06/27",
                itemTypeIcon = R.drawable.ic_element_dendro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 30,
                name = "Navia",
                region = Region.FONTAINE,
                iconBgColor = R.drawable.ic_geo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic_navia.png",
                birthdate = "08/16",
                itemTypeIcon = R.drawable.ic_element_geo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 31,
                name = "Neuvillette",
                region = Region.FONTAINE,
                iconBgColor = R.drawable.ic_hydro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-neuvillette.png",
                birthdate = "12/18",
                itemTypeIcon = R.drawable.ic_element_hydro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 32,
                name = "Nilou",
                region = Region.SUMERU,
                iconBgColor = R.drawable.ic_hydro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-nilou.png",
                birthdate = "12/03",
                itemTypeIcon = R.drawable.ic_element_hydro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 33,
                name = "Qiqi",
                region = Region.LIYUE,
                iconBgColor = R.drawable.ic_cryo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-qiqi.png",
                birthdate = "03/03",
                itemTypeIcon = R.drawable.ic_element_cryo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 34,
                name = "Raiden Shogun",
                region = Region.INAZUMA,
                iconBgColor = R.drawable.ic_electro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-raiden.png",
                birthdate = "06/26",
                itemTypeIcon = R.drawable.ic_element_electro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 35,
                name = "Sangonomiya Kokomi",
                region = Region.INAZUMA,
                iconBgColor = R.drawable.ic_hydro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-kokomi.png",
                birthdate = "02/22",
                itemTypeIcon = R.drawable.ic_element_hydro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 36,
                name = "Shenhe",
                region = Region.LIYUE,
                iconBgColor = R.drawable.ic_cryo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-shenhe.png",
                birthdate = "03/10",
                itemTypeIcon = R.drawable.ic_element_cryo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 37,
                name = "Sigewinne",
                region = Region.FONTAINE,
                iconBgColor = R.drawable.ic_hydro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic_sigewinne.png",
                birthdate = "03/30",
                itemTypeIcon = R.drawable.ic_element_hydro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 38,
                name = "Tartaglia",
                region = Region.SNEZHNAYA,
                iconBgColor = R.drawable.ic_hydro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-tartaglia.png",
                birthdate = "07/20",
                itemTypeIcon = R.drawable.ic_element_hydro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 39,
                name = "Tighnari",
                region = Region.SUMERU,
                iconBgColor = R.drawable.ic_dendro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-tighnari.png",
                birthdate = "09/21",
                itemTypeIcon = R.drawable.ic_element_dendro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 40,
                name = "Wanderer",
                region = Region.SUMERU,
                iconBgColor = R.drawable.ic_anemo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-wanderer.png",
                birthdate = "11/18",
                itemTypeIcon = R.drawable.ic_element_anemo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 41,
                name = "Wriothesley",
                region = Region.FONTAINE,
                iconBgColor = R.drawable.ic_cryo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-wriothesley.png",
                birthdate = "11/23",
                itemTypeIcon = R.drawable.ic_element_cryo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 42,
                name = "Xianyun",
                region = Region.LIYUE,
                iconBgColor = R.drawable.ic_anemo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic_xianyun.png",
                birthdate = "04/11",
                itemTypeIcon = R.drawable.ic_element_anemo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 43,
                name = "Xiao",
                region = Region.LIYUE,
                iconBgColor = R.drawable.ic_anemo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-xiao.png",
                birthdate = "04/17",
                itemTypeIcon = R.drawable.ic_element_anemo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 44,
                name = "Xilonen",
                region = Region.NATLAN,
                iconBgColor = R.drawable.ic_geo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic_xilonen.png",
                birthdate = "03/13",
                itemTypeIcon = R.drawable.ic_element_geo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 45,
                name = "Yae Miko",
                region = Region.INAZUMA,
                iconBgColor = R.drawable.ic_electro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-yaemiko.png",
                birthdate = "06/27",
                itemTypeIcon = R.drawable.ic_element_electro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 46,
                name = "Yelan",
                region = Region.LIYUE,
                iconBgColor = R.drawable.ic_hydro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-yelan.png",
                birthdate = "07/20",
                itemTypeIcon = R.drawable.ic_element_hydro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 47,
                name = "Yoimiya",
                region = Region.INAZUMA,
                iconBgColor = R.drawable.ic_pyro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-yoimiya.png",
                birthdate = "06/21",
                itemTypeIcon = R.drawable.ic_element_pyro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 48,
                name = "Zhongli",
                region = Region.LIYUE,
                iconBgColor = R.drawable.ic_geo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-zhongli.png",
                birthdate = "12/31",
                itemTypeIcon = R.drawable.ic_element_geo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 49,
                name = "Mavuika",
                region = Region.NATLAN,
                iconBgColor = R.drawable.ic_pyro_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic_mavuika.png",
                birthdate = "08/28",
                itemTypeIcon = R.drawable.ic_element_pyro,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 50,
                name = "Venti",
                region = Region.MONDSTADT,
                iconBgColor = R.drawable.ic_anemo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic-venti.png",
                birthdate = "06/16",
                itemTypeIcon = R.drawable.ic_element_anemo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            ),
            Item(
                id = 51,
                name = "Yumemizuki Mizuki",
                region = Region.INAZUMA,
                iconBgColor = R.drawable.ic_anemo_bg,
                icon = "https://ik.imagekit.io/h6nj8eluh/character-icons/ic_mizuki.png",
                birthdate = "03/16",
                itemTypeIcon = R.drawable.ic_element_anemo,
                rarity = 5,
                rank = 0,
                type = ItemType.CHARACTER
            )
        )
    }
}
